#! /usr/bin/env python
# simple place holder for real application, enables early usage
#   Author: Thuan Tran improved to inspect multiple spk files
#           Put files in quotes
import cPickle
import perfstats as ps

from glob import glob
from sys import argv


if __name__ == '__main__':
     i = 0
     for filename in glob(argv[1]):
         i=i+1
         print "File %d : %s " % (i,filename)
         f = open(filename,'r')
         pickle = cPickle.load(f)
         print 'scores'
         print pickle.result.generateCSVRows()
         print 'power'
         print pickle.profiles['extech'].getStats()
         print 'cpu profiler'
         print pickle.profiles['vmstat'].getStats()
         f.close()
